export const authActions = {
  AUTH_SIGN_UP: 'AUTH_SIGN_UP',
  AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  AUTH_SIGN_UP_FAIL: 'AUTH_SIGN_UP_FAIL',

  AUTH_SIGN_IN: 'AUTH_SIGN_IN',
  AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
  AUTH_SIGN_IN_FAIL: 'AUTH_SIGN_IN_FAIL'
}
