export const cartActions = {
  APPEND_ITEM_TO_CART: 'APPEND_ITEM_TO_CART',
  REMOVE_ITEM_TO_CART: 'REMOVE_ITEM_TO_CART',
  DECREMENT_ITEM_TO_CART: 'DECREMENT_ITEM_TO_CART',
  CART_DESTROY: 'CART_DESTROY'
}
