export const productsActions = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_SUCCESS: 'LOAD_PRODUCTS_SUCCESS',
  LOAD_PRODUCTS_FAIL: 'LOAD_PRODUCTS_FAIL',
  LOAD_SAVE_PRODUCT: 'LOAD_SAVE_PRODUCT',
  LOAD_SAVE_PRODUCT_SUCCESS: 'LOAD_SAVE_PRODUCT_SUCCESS',
  LOAD_SAVE_PRODUCT_FAIL: 'LOAD_SAVE_PRODUCT_FAIL',

  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',

  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL'
}
