### Register
POST http://localhost:3007/auth/register
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "123456@"
}

### Login
POST http://localhost:3007/auth/login
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "123456@"
}


### Profile
GET http://localhost:3007/auth/profile
Content-Type: application/json
Authorization: Bearer 
