### Register
POST http://localhost:3007/auth/register
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "1234@"
}

### Login
POST http://localhost:3007/auth/login
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "1234@"
}


### Profile
GET http://localhost:3007/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmIxODE1Y2ZlZTNmZGZjMTcxMTY0NiIsImlhdCI6MTYzMDIxNTY3MX0.3SKAbUPucDuZLf59ITkzTSO8-HUEk_ydMrtKn6dDfQ8
