### Register
POST http://localhost:3007/auth/register
Content-Type: application/json

{
  "email": "test123@test.com",
  "password": "123456@"
}

### Login
POST http://localhost:3007/auth/login
Content-Type: application/json

{
  "email": "te@test.com",
  "password": "123456@"
}


### Profile
GET http://localhost:3007/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmQ5NDczMjYyM2I4MjcwY2FmNjhkMyIsImlhdCI6MTYzMDM3NzEwMX0.Rw24DcpX-PCf8mS6FQMsTdVW8ht1DejFsFVHQtBZyzg
